# environment.yaml

name: get_data
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - anaconda
  - pip
  - pandas
  - scipy
  - sklearn
  - python-louvain
  - numpy<2.0
  - pip:
    - GEOparse
